apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdjuno.fullname" . }}
  labels:
    {{- include "bdjuno.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: bactions
  selector:
    {{- include "bdjuno.selectorLabels" . | nindent 4 }}
